# TPI - Organización Empresarial

## Sistema de Gestión de Vacaciones para BCH Sistemas

### Alumna
Brisa Chirino

### Materia
Organización Empresarial

## Descripción

El presente proyecto consiste en el diseño y simulación de un sistema de gestión de vacaciones mediante un chatbot para la empresa ficticia BCH Sistemas.

La solución propuesta busca automatizar el proceso de solicitud de vacaciones, permitiendo que los empleados puedan realizar sus pedidos de manera rápida y eficiente, reduciendo la carga administrativa del área de Recursos Humanos.

El chatbot permite:

- Validar la identidad del empleado mediante legajo.
- Consultar información almacenada en una base de datos.
- Verificar días disponibles.
- Solicitar fechas y cantidad de días.
- Aplicar reglas de negocio.
- Enviar solicitudes al supervisor cuando corresponda.
- Aprobar o rechazar solicitudes.
- Actualizar la información de vacaciones disponible.

## Tecnologías

- Python
- Excel (Base de datos simulada)
- BPMN 2.0
- GitHub

## Estructura del proyecto

TPI_OE/
├── codigo
├── documentacion
├── diagrama
├── capturas_ia
├── base_datos
├── README.md
└── .gitignore

## Estado

Proyecto en desarrollo.